### ISSUE TITLE
Feature Request: FaceTime Audio Call

### ISSUE THREAD

**Issue by joshuabc** [guiguan/Uni-Call#15]
On OS X Yosemite, we now have the option to place an audio call with FaceTime using our iOS devices. It looks like the Uni-Call workflow for FaceTime defaults to a video call right now. It would be great if there was an option to immediately place the call via FaceTime Audio.

Thanks for your excellent work!

**Comment by guiguan** [comment]
The new version will be released today or tomorrow. It includes FaceTime audio/video calls, Yosemite iPhone (handoff) call, Messages text and more. :)

Best regards,
Guan

**Comment by joshuabc** [comment]
Very exciting @guiguan! Thanks!

**Comment by guiguan** [comment]
Please check out the new version. Just released. Sorry for the delay :)
