### ISSUE TITLE
Possibly make more hackable

### ISSUE THREAD

**Issue by kbrock** [guiguan/Uni-Call#19]
Hello,

This program is great. Found it on alfred forumns.

I noticed that the phone numbers chosen don't take into account that the home phone number will probably not work with messages, but the cell or iPhone will. I would prefer uni-call to be smart enough to choose and not have to label every user with a custom label (that will look weird on my iphone)

So I wanted to go in and hack it, but while browsing on GitHub, found most of the sources to be in objective-c or a binary format.

I had a few suggestions for making this more approachable and modifiable by users. Not sure if any of these ideas work for you:
1. put text files (instead of binary) into source control.
2. Update makefile to actually build the workflow and binaries.
3. Move the code that takes input and processes it out of objective-c and into a scripting language like ruby (or bash, python, php, ...). That is more easily edited by users.

It is possible that I am not understanding the code, so maybe the answer is to just add a few comments to the [README.md][] .

Thank you for the useful product.
If you would like help with any of these tasks, just ask and I will help where I can

**Comment by guiguan** [comment]
Hi, @kbrock Thanks for reminding me how terribly I had structured this project :D Very nice suggestions, I will try my best to update it in the next few days.
